language: python
python:
  - "3.7"
    dist: xenial  # required for Python 3.7
    sudo: true    # required for Python 3.7
matrix:
  allow_failures:
    - 3.7

services:
  - mongodb
  - redis-server

before_script:
  - "pip install -U pip setuptools pytest pylint flake8"
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

script:
  - "pip install --editable ."
  - "pytest tests/ -s -v --capture=no"
  - "pylint appkernel"

before_deploy:
  - "python setup.py build -vf"

#  deploy:
#  - provider: pypi
#    user: $REPO_USER
#    password: $REPO_PASS
#    distributions: "bdist_wheel sdist"
